BOOKS = [
  {
    name:   "Haskell",
    author: "Wikibooks.org",
    path:   "Haskell.pdf",
    page:   257,
    pages:  611,
  },
  {
    name:   "Learning Java 4th Edition",
    author: "Patrick Niemeyer & Daniel Leuck",
    path:   "learning_java_fourth_edition.pdf",
    page:   393,
    pages:  1010,
  },
  {
    name:   "Erlang Programming",
    author: "Francesco Cesarini & Simon Thompson",
    path:   "erlang_programming.pdf",
    page:   139,
    pages:  496,
  },
  {
    name:   "Clean Code",
    author: "Robert C. Martin",
    path:   "Clean_Code_-_A_Handbook_of_Agile_Software_Craftsmanship.pdf",
    page:   114,
    pages:  462,
  },
  {
    name:   "Haskell and Yesod",
    author: "Michael Snoyman",
    path:   "Haskell and Yesod.pdf",
    page:   63,
    pages:  296,
  },
  {
    name:   "The C Programming Language 2nd Edition",
    author: "Brian W. Kernighan & Dennis M. Ritchie",
    path:   "Ritchie-Kernighan-The_C_Programming_Language_2_ed_.pdf",
    page:   54,
    pages:  288,
  },
  {
    name:   "Programming Python 4th Edition",
    author: "Mark Lutz",
    path:   "programming_python_4th_edition.pdf",
    page:   216,
    pages:  1628,
  },
  {
    name:   "21st Century C",
    author: "Ben Klemens",
    path:   "21st_century_c.pdf",
    page:   39,
    pages:  298,
  },
  {
    name:   "Programming Erlang",
    author: "Joe Armstrong",
    path:   "Programming_Erlang.pdf",
    page:   66,
    pages:  526,
  },
  {
    name:   "Learning Python 5th Edition",
    author: "Mark Lutz",
    path:   "learning_python_fifth_edition.pdf",
    page:   186,
    pages:  1594,
  },
  {
    name:   "Learning Cocoa with Objective-C",
    author: "Paris Buttfield-Addison & Jonathon Manning",
    path:   "learning_cocoa_with_objective-c_3rd_edition.pdf",
    page:   35,
    pages:  360,
  },
  {
    name:   "The Scheme Programming Language, 4th Edition",
    author: "R. Kent Dybvig",
    path:   "The.Scheme.Programming.Language.4th.Edition.pdf",
    page:   31,
    pages:  400,
  },
  {
    name:   "How to Design Programs, Second Edition",
    author: "Felleisen, Findler, Flatt & Krishnamurthi",
    path:   "http://www.ccs.neu.edu/home/matthias/HtDP2e/part_prologue.html#string-append",
    page:   1,
    pages:  13,
  },
  {
    name:   "The Racket Guide",
    author: "M. Flatt, R. B. Findler, PLT",
    path:   "Racket-Guide.pdf",
    page:   11,
    pages:  369,
  },
  {
    name:   "PMI-80 (Assembly)",
    author: "Ing. Jaroslav Vlach",
    path:   "pmi80_kniha.pdf",
    page:   0,
    pages:  108,
  },
  {
    name:   "The Art of Assembly Language 2nd Edition",
    author: "Randall Hyde",
    path:   "the_art_of_assembly_language_2nd_edition.pdf",
    page:   0,
    pages:  764,
  },
  {
    name:   "Write Great Code",
    author: "Randall Hyde",
    path:   "write_great_code_volume_1.pdf",
    page:   0,
    pages:  461,
  },
  {
    name:   "Mobile First",
    author: "Luke Wroblewski",
    path:   "mobile_first.pdf",
    page:   0,
    pages:  138,
  },
  {
    name:   "Responsive Web Design",
    author: "Ethan Marcotte",
    path:   "responsive_web_design.pdf",
    page:   0,
    pages:  157,
  },
  {
    name:   "Guide to Better Smalltalk",
    author: "Kent Beck",
    path:   "Kent_Becks_guide_to_better_Smalltalk.pdf",
    page:   0,
    pages:  427,
  },
  {
    name:   "ANSI Common Lisp",
    author: "Paul Graham",
    path:   "ANSI_Common_Lisp.pdf",
    page:   0,
    pages:  450,
  },
  {
    name:   "On Lisp: Advanced Techniques for Common Lisp",
    author: "Paul Graham",
    path:   "On_Lisp.pdf",
    page:   0,
    pages:  426,
  },
  {
    name:   "Introducing Erlang",
    author: "Simon St. Laurent",
    path:   "introducing_erlang.pdf",
    page:   201,
    pages:  201,
  },
  {
    name:   "Learning Python 4th Edition",
    author: "Mark Lutz",
    path:   "learning_python_fourth_edition.pdf",
    page:   1213,
    pages:  1213,
  },
  {
    name:   "Realm of Racket",
    author: "D. V. Horn, C. Barski, M. Felleisen",
    path:   "Realm-of-Racket.pdf",
    page:   316,
    pages:  316,
  },
]
